// <auto-generated />
using System;
using Calistenia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Calistenia.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231214000353_in")]
    partial class @in
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Calistenia.Models.Exercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exercicio_Facilitado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GpMuscular_1")
                        .HasColumnType("int");

                    b.Property<int>("GpMuscular_2")
                        .HasColumnType("int");

                    b.Property<int>("GpMuscular_3")
                        .HasColumnType("int");

                    b.Property<int>("GpMuscular_4")
                        .HasColumnType("int");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dificuldade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TB_EXERCICIO");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = " ",
                            Exercicio_Facilitado = "",
                            GpMuscular_1 = 1,
                            GpMuscular_2 = 2,
                            GpMuscular_3 = 4,
                            GpMuscular_4 = 0,
                            Modo = "Repetição",
                            Nome = "Flexão Padrão",
                            Tipo = "PUSH",
                            dificuldade = 2
                        },
                        new
                        {
                            Id = 2,
                            Descricao = " ",
                            Exercicio_Facilitado = "",
                            GpMuscular_1 = 1,
                            GpMuscular_2 = 2,
                            GpMuscular_3 = 4,
                            GpMuscular_4 = 5,
                            Modo = "Repetição",
                            Nome = "Flexão Pike",
                            Tipo = "PUSH",
                            dificuldade = 3
                        },
                        new
                        {
                            Id = 3,
                            Descricao = " ",
                            Exercicio_Facilitado = "",
                            GpMuscular_1 = 10,
                            GpMuscular_2 = 11,
                            GpMuscular_3 = 0,
                            GpMuscular_4 = 0,
                            Modo = "Repetição",
                            Nome = "Elevação de Pernas na barra",
                            Tipo = "CORE",
                            dificuldade = 3
                        },
                        new
                        {
                            Id = 4,
                            Descricao = " ",
                            Exercicio_Facilitado = "",
                            GpMuscular_1 = 6,
                            GpMuscular_2 = 3,
                            GpMuscular_3 = 0,
                            GpMuscular_4 = 0,
                            Modo = "Repetição",
                            Nome = "Barra Fixa Pronada",
                            Tipo = "PULL",
                            dificuldade = 3
                        },
                        new
                        {
                            Id = 5,
                            Descricao = " ",
                            Exercicio_Facilitado = "",
                            GpMuscular_1 = 3,
                            GpMuscular_2 = 8,
                            GpMuscular_3 = 6,
                            GpMuscular_4 = 0,
                            Modo = "Repetição",
                            Nome = "Barra Fixa Supinada",
                            Tipo = "PULL",
                            dificuldade = 3
                        },
                        new
                        {
                            Id = 6,
                            Descricao = " ",
                            Exercicio_Facilitado = "",
                            GpMuscular_1 = 9,
                            GpMuscular_2 = 0,
                            GpMuscular_3 = 0,
                            GpMuscular_4 = 0,
                            Modo = "Repetição",
                            Nome = "Flexão Lombar",
                            Tipo = "CORE",
                            dificuldade = 2
                        },
                        new
                        {
                            Id = 7,
                            Descricao = " ",
                            Exercicio_Facilitado = "",
                            GpMuscular_1 = 12,
                            GpMuscular_2 = 0,
                            GpMuscular_3 = 0,
                            GpMuscular_4 = 0,
                            Modo = "Repetição",
                            Nome = "Prancha Lateral",
                            Tipo = "CORE",
                            dificuldade = 2
                        },
                        new
                        {
                            Id = 8,
                            Descricao = " ",
                            Exercicio_Facilitado = "",
                            GpMuscular_1 = 15,
                            GpMuscular_2 = 14,
                            GpMuscular_3 = 0,
                            GpMuscular_4 = 0,
                            Modo = "Repetição",
                            Nome = "Afundos",
                            Tipo = "PERNA",
                            dificuldade = 2
                        },
                        new
                        {
                            Id = 9,
                            Descricao = " ",
                            Exercicio_Facilitado = "",
                            GpMuscular_1 = 16,
                            GpMuscular_2 = 0,
                            GpMuscular_3 = 0,
                            GpMuscular_4 = 0,
                            Modo = "Repetição",
                            Nome = "Elevação de Calcanhar",
                            Tipo = "PERNA",
                            dificuldade = 2
                        });
                });

            modelBuilder.Entity("Calistenia.Models.RepSerie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Repeticao")
                        .HasColumnType("int");

                    b.Property<int>("Serie")
                        .HasColumnType("int");

                    b.Property<int>("exercicioId")
                        .HasColumnType("int");

                    b.Property<int?>("treinoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("exercicioId");

                    b.HasIndex("treinoId");

                    b.ToTable("TB_REPSERIE");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Repeticao = 8,
                            Serie = 3,
                            exercicioId = 9,
                            treinoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Repeticao = 10,
                            Serie = 2,
                            exercicioId = 9,
                            treinoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Repeticao = 12,
                            Serie = 2,
                            exercicioId = 9,
                            treinoId = 1
                        });
                });

            modelBuilder.Entity("Calistenia.Models.Treino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rep_1")
                        .HasColumnType("int");

                    b.Property<int?>("Rep_10")
                        .HasColumnType("int");

                    b.Property<int?>("Rep_2")
                        .HasColumnType("int");

                    b.Property<int?>("Rep_3")
                        .HasColumnType("int");

                    b.Property<int?>("Rep_4")
                        .HasColumnType("int");

                    b.Property<int?>("Rep_5")
                        .HasColumnType("int");

                    b.Property<int?>("Rep_6")
                        .HasColumnType("int");

                    b.Property<int?>("Rep_7")
                        .HasColumnType("int");

                    b.Property<int?>("Rep_8")
                        .HasColumnType("int");

                    b.Property<int?>("Rep_9")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_TREINOS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "ta potente essa perna fibrada ai meu mano",
                            Nome = "treino de Perna",
                            Rep_1 = 1,
                            Rep_2 = 3,
                            Tipo = "PERNA"
                        });
                });

            modelBuilder.Entity("Calistenia.Usuario", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("DataAcesso")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Acesso");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("Latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("Longitude");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("PassWord_H");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("PassWord_S");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Usuario")
                        .HasColumnName("Perfil");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("U_Name");

                    b.HasKey("Id");

                    b.ToTable("TB_USUARIO", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "arturdiniz06@gmail.com",
                            Latitude = -23.520024100000001,
                            Longitude = -46.596497999999997,
                            PasswordHash = new byte[] { 3, 7, 217, 60, 2, 26, 229, 204, 35, 62, 30, 137, 245, 31, 166, 166, 183, 229, 196, 27, 70, 147, 202, 134, 228, 114, 63, 113, 152, 184, 154, 209, 145, 231, 13, 90, 140, 250, 228, 194, 120, 206, 99, 120, 101, 253, 250, 17, 131, 196, 70, 55, 232, 251, 64, 88, 154, 94, 166, 89, 199, 183, 189, 103 },
                            PasswordSalt = new byte[] { 227, 121, 122, 119, 21, 228, 18, 169, 44, 151, 192, 122, 44, 23, 197, 26, 80, 69, 179, 135, 0, 155, 57, 2, 100, 64, 218, 128, 1, 103, 106, 91, 128, 115, 60, 172, 134, 10, 168, 203, 33, 152, 79, 219, 161, 46, 0, 120, 56, 229, 189, 152, 63, 20, 169, 225, 97, 91, 6, 25, 94, 92, 197, 12, 149, 90, 22, 229, 158, 59, 63, 187, 168, 156, 215, 220, 201, 57, 148, 152, 20, 72, 144, 129, 32, 111, 95, 227, 7, 22, 225, 34, 214, 74, 188, 125, 215, 49, 79, 20, 137, 222, 242, 166, 128, 22, 188, 62, 12, 38, 104, 27, 114, 79, 116, 212, 75, 67, 104, 208, 241, 233, 57, 68, 162, 98, 233, 137 },
                            Perfil = "Admin",
                            Username = "UsuarioAdmin"
                        });
                });

            modelBuilder.Entity("Calistenia.Models.RepSerie", b =>
                {
                    b.HasOne("Calistenia.Models.Exercicio", "Exercicios")
                        .WithMany("RepSeries")
                        .HasForeignKey("exercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Calistenia.Models.Treino", "Treinos")
                        .WithMany("RepSeries")
                        .HasForeignKey("treinoId");

                    b.Navigation("Exercicios");

                    b.Navigation("Treinos");
                });

            modelBuilder.Entity("Calistenia.Models.Treino", b =>
                {
                    b.HasOne("Calistenia.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Calistenia.Models.Exercicio", b =>
                {
                    b.Navigation("RepSeries");
                });

            modelBuilder.Entity("Calistenia.Models.Treino", b =>
                {
                    b.Navigation("RepSeries");
                });
#pragma warning restore 612, 618
        }
    }
}
